-- MySQL Script generated by MySQL Workbench
-- Sun Oct  8 14:13:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pi2db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pi2db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pi2db` DEFAULT CHARACTER SET utf8 ;
USE `pi2db` ;

-- -----------------------------------------------------
-- Table `pi2db`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi2db`.`usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `email` VARCHAR(250) NULL,
  `senha` VARCHAR(100) NULL,
  `token` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi2db`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi2db`.`cliente` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario_id` INT UNSIGNED NULL,
  `nome` VARCHAR(100) NULL,
  `saldo` DECIMAL(8,2) NULL,
  `cpf` CHAR(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `pi2db`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi2db`.`linha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi2db`.`linha` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `origem` VARCHAR(100) NULL,
  `destino` VARCHAR(100) NULL,
  `horarioPartida` TIME NULL,
  `horarioChegada` TIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi2db`.`motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi2db`.`motorista` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `foto` VARCHAR(250) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi2db`.`onibus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi2db`.`onibus` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `placa` CHAR(7) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi2db`.`viagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi2db`.`viagem` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `linha_id` INT UNSIGNED NULL,
  `motorista_id` INT UNSIGNED NULL,
  `onibus_id` INT UNSIGNED NULL,
  `dataPartida` DATETIME NULL,
  `dataChegada` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_viagem_linha1_idx` (`linha_id` ASC) VISIBLE,
  INDEX `fk_viagem_motorista1_idx` (`motorista_id` ASC) VISIBLE,
  INDEX `fk_viagem_onibus1_idx` (`onibus_id` ASC) VISIBLE,
  CONSTRAINT `fk_viagem_linha1`
    FOREIGN KEY (`linha_id`)
    REFERENCES `pi2db`.`linha` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viagem_motorista1`
    FOREIGN KEY (`motorista_id`)
    REFERENCES `pi2db`.`motorista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viagem_onibus1`
    FOREIGN KEY (`onibus_id`)
    REFERENCES `pi2db`.`onibus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi2db`.`embarque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi2db`.`embarque` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cliente_id` INT UNSIGNED NULL,
  `viagem_id` INT UNSIGNED NULL,
  `tarifa` DECIMAL(8,2) NULL,
  `horario` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_has_viagem_viagem1_idx` (`viagem_id` ASC) VISIBLE,
  INDEX `fk_cliente_has_viagem_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_viagem_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `pi2db`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_viagem_viagem1`
    FOREIGN KEY (`viagem_id`)
    REFERENCES `pi2db`.`viagem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
